- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - docker_service_manage | bool
    - ansible_system != 'Darwin'

- name: restart iptables
  service:
    name: netfilter-persistent
    state: restarted
  when: ansible_os_family == 'Debian'

