- name: users | simone | add public ansible key
  tags: always, simone, ssh, ssh-keys, users
  authorized_key:
    user: simone
    key: "{{ item }}"
  with_file:
    - users/simone/ssh/simone_id_ed25519.pub

- name: users | simone | add sudoers file for simone
  tags: always, simone, ssh, ssh-keys, user, sudo
  copy:
    src: users/sudoers_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440
