- name: system setup | packages | install bpytop (Linux)
  tags: bpytop,packages,python
  package:
    name: bpytop
    state: present
    update_cache: true
  when: ansible_os_family != "Darwin"

- name: system setup | packages | install bpytop MacOS
  tags: bpytop, packages, python
  community.general.homebrew:
    name: bpytop
    state: present
  when: ansible_os_family == "Darwin"

- name: system setup | packages | install fwupd
  tags: fwupd, packages
  package:
    name: fwupd
    state: present
    update_cache: true
  when: ansible_os_family != "Darwin"
