- name: pip install packages (Linux)
  pip:
    name: "{{ pip_packages }}"
  when: ansible_os_family != "Darwin"

- name: pip install packages (macOS)
  become: false
  pip:
    name: "{{ pip_packages }}"
    executable: /opt/homebrew/bin/pip3
  when: ansible_os_family == "Darwin"
