- name: software | development packages | install packages (Linux)
  tags: dev, development, packages, python
  package:
    name:
      - git
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_virtualenv_package }}"
      - "{{ python_setuptools }}"
  when: ansible_os_family != "Darwin"

- name: software | development packages | install packages (macOS)
  tags: dev, development, packages, python
  become: false
  community.general.homebrew:
    name:
      - git
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_virtualenv_package }}"
      - "{{ python_setuptools }}"
    state: present
  when: ansible_os_family == "Darwin"
