- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest
  when:
    - ansible_os_family != "Darwin"
    - cron_package is defined
    - cron_package | length > 0

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"
