- name: system setup | memory | adjust current swappiness
  tags: swappiness, sysctl, system, setup
  lineinfile:
    path: /etc/sysctl.conf
    create: yes
    regexp: '^vm\.swappiness\s*='
    line: "vm.swappiness={{ swappiness_value }}"
  register: swappiness
  when: ansible_system == "Linux"

- name: system setup | memory | apply swappiness
  tags: swappiness, sysctl, system, setup
  command: sysctl -w vm.swappiness={{ swappiness_value }}
  when:
    - ansible_system == "Linux"
    - swappiness.changed

- name: system setup | memory | install earlyoom package
  tags: earlyoom, packages, system, setup
  package:
    name: earlyoom
    state: latest
  when: ansible_system == "Linux"

- name: system setup | memory | enable and start earlyoom
  tags: earlyoom, packages, system, setup
  service:
    name: earlyoom
    enabled: yes
    state: started
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
